# Site settings
title: Antioch Baptist Church
email: info@antiochbaptist.online
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://antiochbaptist.online" # the base hostname & protocol for your site

# twitter_username:
facebook_username: 100064530106496
sms_phonenumber: 8334587182

# Build settings
markdown: kramdown
